all: linreg.dll minimal.dll

linreg.dll: linreg.cpp
	Rscript --vanilla -e "TMB::compile('linreg.cpp', '-O1 -g', safebounds = FALSE, safeunload = FALSE, DLLFLAGS = '')"

minimal.dll: minimal.cpp
	Rscript --vanilla -e "TMB::compile('minimal.cpp', '-O1 -g', safebounds = FALSE, safeunload = FALSE, DLLFLAGS = '')"

clean:
	rm -rf *.o
	rm -rf *.dll
